name: GitHub Action Deploy
on:
  push:
    branches:
    - baseline

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: baseline rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude ".*" --exclude "scripts" --exclude "jsconfig.json"
        # path: src/
        remote_path: /home/zsx/cqa_baseline_rsync/
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
